mod network;

use network::PreviousScan;
use arqenor_core::models::{
    alert::{Alert, Severity},
    persistence::PersistenceEntry,
    process::{ProcessInfo, ProcessScore, ScoreFactor},
};
use arqenor_platform::{new_persistence_detector, new_process_monitor};
use serde::{Deserialize, Serialize};
use std::{
    collections::{HashMap, VecDeque},
    sync::Mutex,
};
use tauri::{Emitter, Manager, State};

// ── App state ─────────────────────────────────────────────────────────────────

#[derive(Default)]
pub struct AppState {
    /// IP → open ports from the last completed scan
    pub previous_scan: Mutex<PreviousScan>,
    /// ETW events ring buffer — last 500 events from the real-time session
    pub etw_events: Mutex<VecDeque<EtwEventDto>>,
    /// Alerts generated by the ETW monitor and other detection engines
    pub alerts: Mutex<Vec<Alert>>,
}

const ETW_RING_CAPACITY: usize = 500;

// ── ETW event DTO (serialisable pour Tauri) ───────────────────────────────────

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EtwEventDto {
    /// Short provider name, e.g. `"PowerShell"` or `"Kernel-Network"`
    pub provider_label: String,
    /// Full GUID string `{XXXXXXXX-…}`
    pub provider_guid:  String,
    pub event_id:       u16,
    pub pid:            u32,
    pub tid:            u32,
    /// ISO-8601 timestamp converted from Windows FILETIME
    pub timestamp:      String,
    pub level:          u8,
    pub keyword:        u64,
    /// Size of the raw UserData payload (TDH-parse deferred)
    pub data_size:      usize,
    pub description:    String,
}

/// Short display label for known provider GUIDs (matched on data1).
fn provider_label(guid: &str) -> &'static str {
    match guid.get(1..9).unwrap_or("") {
        "22FB2CD6" => "Kernel-Process",
        "A0C1853B" => "PowerShell",
        "54849625" => "Security-Audit",
        "1C95126E" => "DNS-Client",
        "1418EF04" => "WMI-Activity",
        "DE7B24EA" => "TaskScheduler",
        "7DD42A49" => "Kernel-Network",
        "EDD08927" => "Kernel-File",
        "70EB4F03" => "Kernel-Registry",
        _          => "Unknown",
    }
}

/// Convert Windows FILETIME (100-ns intervals since 1601-01-01) to ISO-8601.
fn filetime_to_iso(ft: i64) -> String {
    use chrono::TimeZone;
    // Offset between 1601-01-01 and 1970-01-01 in 100-ns units
    const EPOCH_DIFF: i64 = 116_444_736_000_000_000;
    let unix_100ns = ft.saturating_sub(EPOCH_DIFF);
    let secs  = unix_100ns / 10_000_000;
    let nanos = ((unix_100ns % 10_000_000) * 100).max(0) as u32;
    chrono::Utc
        .timestamp_opt(secs, nanos)
        .single()
        .unwrap_or_else(chrono::Utc::now)
        .to_rfc3339()
}

/// Classify an ETW event into an Alert (returns None for low-value events).
fn classify_etw_to_alert(ev: &EtwEventDto) -> Option<Alert> {
    let tag = ev.provider_guid.get(1..9)?;
    let (severity, rule_id, attack_id, kind) = match (tag, ev.event_id) {
        ("A0C1853B", 4104) => (Severity::High,   "ETW-1001", "T1059.001", "PowerShell ScriptBlock Execution"),
        ("54849625", 4698) => (Severity::High,   "ETW-1002", "T1053.005", "Scheduled Task Created"),
        ("54849625", 4702) => (Severity::Medium, "ETW-1003", "T1053.005", "Scheduled Task Modified"),
        ("54849625", 4720) => (Severity::High,   "ETW-1004", "T1136",     "User Account Created"),
        ("54849625", 4732) => (Severity::High,   "ETW-1005", "T1078",     "User Added to Local Group"),
        ("1418EF04", 5861) => (Severity::High,   "ETW-1006", "T1047",     "WMI Event Consumer Registered"),
        ("DE7B24EA", 106)  => (Severity::Medium, "ETW-1007", "T1053.005", "Scheduled Task Launched"),
        ("70EB4F03", 1)    => (Severity::Low,    "ETW-1008", "T1112",     "Registry Key Created (Kernel)"),
        ("70EB4F03", 3)    => (Severity::Low,    "ETW-1009", "T1112",     "Registry Value Set (Kernel)"),
        _ => return None,
    };

    let mut metadata = HashMap::new();
    metadata.insert("pid".into(),         ev.pid.to_string());
    metadata.insert("event_id".into(),    ev.event_id.to_string());
    metadata.insert("provider".into(),    ev.provider_label.clone());
    metadata.insert("etw_desc".into(),    ev.description.clone());

    Some(Alert {
        id:          uuid::Uuid::new_v4(),
        severity,
        kind:        kind.to_string(),
        message:     format!("{kind} — PID {} (ETW {})", ev.pid, ev.event_id),
        occurred_at: chrono::Utc::now(),
        metadata,
        rule_id:     Some(rule_id.to_string()),
        attack_id:   Some(attack_id.to_string()),
    })
}

// ── Process scoring ───────────────────────────────────────────────────────────

fn looks_random(name: &str) -> bool {
    let stem: String = name.chars().take_while(|&c| c != '.').collect();
    if stem.len() < 8 { return false; }
    let vowels = stem.chars().filter(|c| "aeiouAEIOU".contains(*c)).count();
    let ratio = vowels as f32 / stem.len() as f32;
    ratio < 0.1
}

fn score_process(p: &ProcessInfo, all_procs: &[ProcessInfo]) -> ProcessScore {
    let mut factors: Vec<ScoreFactor> = Vec::new();

    if let Some(path) = &p.exe_path {
        let low = path.to_lowercase();

        // G1 — Temp directory
        if low.contains("\\temp\\") || low.contains("\\appdata\\local\\temp") {
            factors.push(ScoreFactor {
                name:      "Executes from temp directory".to_string(),
                points:    5,
                attack_id: Some("T1036.005".to_string()),
            });
        }

        // G2 — System process masquerading from unexpected path
        let sys = [
            "svchost.exe", "lsass.exe", "csrss.exe", "winlogon.exe",
            "wininit.exe", "services.exe", "spoolsv.exe", "explorer.exe",
        ];
        if sys.iter().any(|&s| p.name.to_lowercase() == s)
            && !low.contains("\\windows\\system32\\")
            && !low.contains("\\windows\\syswow64\\")
            && !low.ends_with("\\windows\\explorer.exe")
        {
            factors.push(ScoreFactor {
                name:      "System process masquerading from unexpected path".to_string(),
                points:    8,
                attack_id: Some("T1036.005".to_string()),
            });
        }

        // G3 — Executable from unsigned-path location
        if !low.contains("c:\\windows\\") && !low.contains("c:\\program files") {
            factors.push(ScoreFactor {
                name:      "Executable from unsigned-path location".to_string(),
                points:    3,
                attack_id: Some("T1553.002".to_string()),
            });
        }

        // G6 — Executable from network share (UNC path)
        if path.starts_with("\\\\") {
            factors.push(ScoreFactor {
                name:      "Executes from network share (PsExec-style)".to_string(),
                points:    4,
                attack_id: Some("T1021.002".to_string()),
            });
        }
    }

    // G4 — High-entropy filename
    if looks_random(&p.name) {
        factors.push(ScoreFactor {
            name:      "High-entropy process name (possible random malware dropper)".to_string(),
            points:    2,
            attack_id: None,
        });
    }

    // G5 — Spawned by browser or Office application
    let browser_office = [
        "chrome.exe", "firefox.exe", "msedge.exe", "brave.exe", "opera.exe",
        "safari.exe", "WINWORD.EXE", "EXCEL.EXE", "POWERPNT.EXE",
        "outlook.exe", "iexplore.exe",
    ];
    if let Some(parent) = all_procs.iter().find(|pp| pp.pid == p.ppid) {
        if browser_office.iter().any(|&b| parent.name.eq_ignore_ascii_case(b)) {
            factors.push(ScoreFactor {
                name:      "Spawned by browser or Office application".to_string(),
                points:    3,
                attack_id: Some("T1566.001".to_string()),
            });
        }
    }

    let total: u8 = factors.iter().map(|f| f.points).fold(0u8, |acc, p| acc.saturating_add(p));
    ProcessScore { total, factors }
}

fn risk_from_score(score: u8) -> &'static str {
    match score {
        0     => "Normal",
        1     => "Low",
        2..=3 => "Medium",
        4..=7 => "High",
        _     => "Critical",
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProcessRow {
    pub info:    ProcessInfo,
    pub risk:    String,
    pub score:   u8,
    pub factors: Vec<ScoreFactor>,
}

// ── Commands ──────────────────────────────────────────────────────────────────

#[tauri::command]
async fn get_processes() -> Result<Vec<ProcessRow>, String> {
    let monitor = new_process_monitor();
    let raw = monitor.snapshot().await.map_err(|e| e.to_string())?;
    let mut rows: Vec<ProcessRow> = raw.iter().map(|p| {
        let ps = score_process(p, &raw);
        ProcessRow { info: p.clone(), risk: risk_from_score(ps.total).to_string(), score: ps.total, factors: ps.factors }
    }).collect();
    rows.sort_by(|a, b| b.score.cmp(&a.score).then(a.info.name.cmp(&b.info.name)));
    Ok(rows)
}

#[tauri::command]
async fn get_persistence() -> Result<Vec<PersistenceEntry>, String> {
    let detector = new_persistence_detector();
    detector.detect().await.map_err(|e| e.to_string())
}

#[tauri::command]
async fn get_vpn_status() -> Result<Option<network::VpnInfo>, String> {
    let monitor = new_process_monitor();
    let procs = monitor.snapshot().await.map_err(|e| e.to_string())?;
    let names: Vec<String> = procs.into_iter().map(|p| p.name).collect();
    Ok(network::detect_vpn(&names))
}

/// Starts a subnet scan with anomaly detection.
/// Emits:
///   "network-host"       — each host found (HostInfo JSON)
///   "network-scan-done"  — scan complete, no payload
#[tauri::command]
async fn start_network_scan(
    app:   tauri::AppHandle,
    state: State<'_, AppState>,
) -> Result<String, String> {
    let subnets = network::get_lan_subnets();
    let base = subnets.into_iter().next()
        .ok_or_else(|| "No LAN subnet detected".to_string())?;

    let label = format!("{}.{}.{}.x/24", base[0], base[1], base[2]);

    let previous: PreviousScan = state.previous_scan
        .lock()
        .map(|g| g.clone())
        .unwrap_or_default();

    tokio::spawn(async move {
        let mut rx = network::scan_subnet(base, previous);
        let mut new_scan: HashMap<String, Vec<u16>> = HashMap::new();

        while let Some(host) = rx.recv().await {
            new_scan.insert(host.ip.clone(), host.ports.clone());
            let _ = app.emit("network-host", &host);
        }

        let _ = app.emit("network-scan-done", ());

        app.state::<AppState>()
            .previous_scan
            .lock()
            .map(|mut g| { *g = new_scan; })
            .ok();
    });

    Ok(label)
}

#[tauri::command]
async fn get_alerts(state: State<'_, AppState>) -> Result<Vec<Alert>, String> {
    let alerts = state.alerts.lock().map_err(|e| e.to_string())?;
    let mut out = alerts.clone();
    // Most recent first
    out.sort_by(|a, b| b.occurred_at.cmp(&a.occurred_at));
    Ok(out)
}

#[tauri::command]
async fn get_etw_events(state: State<'_, AppState>) -> Result<Vec<EtwEventDto>, String> {
    let ring = state.etw_events.lock().map_err(|e| e.to_string())?;
    // Return most-recent-first (reverse the deque)
    Ok(ring.iter().rev().cloned().collect())
}

#[tauri::command]
fn get_incidents(_state: State<AppState>) -> Vec<serde_json::Value> {
    // Return incidents from the correlation engine.
    // For now, return an empty vec — the wiring agent will connect this.
    vec![]
}

#[tauri::command]
fn scan_memory() -> Vec<serde_json::Value> {
    // Calls arqenor_platform::windows::memory_scan::scan_all_processes()
    // For now, return empty — requires admin privileges.
    #[cfg(target_os = "windows")]
    {
        // TODO: wire to memory_scan::scan_all_processes()
    }
    vec![]
}

#[tauri::command]
fn check_ntdll() -> Vec<serde_json::Value> {
    #[cfg(target_os = "windows")]
    {
        // TODO: wire to ntdll_check::check_ntdll_hooks()
    }
    vec![]
}

#[tauri::command]
fn check_byovd() -> Vec<serde_json::Value> {
    #[cfg(target_os = "windows")]
    {
        // TODO: wire to byovd::scan_byovd()
    }
    vec![]
}

#[tauri::command]
fn get_ioc_stats() -> serde_json::Value {
    // Return empty stats — the wiring agent will connect to IocDatabase.
    serde_json::json!({
        "sha256_count": 0,
        "md5_count": 0,
        "ip_count": 0,
        "domain_count": 0,
        "url_count": 0,
        "total": 0,
        "last_updated": null
    })
}

#[tauri::command]
async fn refresh_ioc_feeds() -> u32 {
    // TODO: wire to ioc::feeds::refresh_all_feeds()
    0
}

// ── App entry point ───────────────────────────────────────────────────────────

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .manage(AppState::default())
        .plugin(tauri_plugin_shell::init())
        .setup(|app| {
            // ── Start ETW real-time consumer (Windows only, requires admin) ───
            #[cfg(target_os = "windows")]
            {
                let handle = app.handle().clone();
                match arqenor_platform::new_etw_consumer() {
                    Ok((consumer, event_rx)) => {
                        std::thread::Builder::new()
                            .name("etw-bridge".into())
                            .spawn(move || {
                                let _guard = consumer; // keep ETW session alive
                                for event in &event_rx {
                                    let dto = EtwEventDto {
                                        provider_label: provider_label(&event.provider_guid).to_string(),
                                        provider_guid:  event.provider_guid.clone(),
                                        event_id:       event.event_id,
                                        pid:            event.pid,
                                        tid:            event.tid,
                                        timestamp:      filetime_to_iso(event.timestamp),
                                        level:          event.level,
                                        keyword:        event.keyword,
                                        data_size:      event.user_data.len(),
                                        description:    event.description.to_string(),
                                    };

                                    let state = handle.state::<AppState>();

                                    // 1. Push to ring buffer
                                    if let Ok(mut ring) = state.etw_events.lock() {
                                        if ring.len() >= ETW_RING_CAPACITY {
                                            ring.pop_front();
                                        }
                                        ring.push_back(dto.clone());
                                    }

                                    // 2. Classify → alert
                                    if let Some(alert) = classify_etw_to_alert(&dto) {
                                        if let Ok(mut alerts) = state.alerts.lock() {
                                            alerts.push(alert);
                                        }
                                    }
                                }
                                tracing::info!("etw-bridge thread exiting");
                            })
                            .ok();
                    }
                    Err(e) => {
                        tracing::warn!("ETW consumer unavailable (requires admin): {e}");
                    }
                }
            }

            Ok(())
        })
        .invoke_handler(tauri::generate_handler![
            get_processes,
            get_persistence,
            get_vpn_status,
            start_network_scan,
            get_alerts,
            get_etw_events,
            get_incidents,
            scan_memory,
            check_ntdll,
            check_byovd,
            get_ioc_stats,
            refresh_ioc_feeds,
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
