//! Build script — generates `libbpf-rs` skeletons for every `*.bpf.c` probe.
//!
//! Linux only. On Windows / macOS this is a no-op so that `cargo check
//! --workspace` keeps working cross-platform (the `loader` module is gated
//! behind `#[cfg(target_os = "linux")]` in `lib.rs`).
//!
//! Generated skeletons land in `$OUT_DIR/{probe}.skel.rs` and are pulled in
//! by `loader.rs` via `include!(concat!(env!("OUT_DIR"), "/{probe}.skel.rs"))`.

#[cfg(target_os = "linux")]
fn main() -> Result<(), Box<dyn std::error::Error>> {
    use libbpf_cargo::SkeletonBuilder;
    use std::path::PathBuf;

    let probes_dir = PathBuf::from("src/probes");
    let out_dir = PathBuf::from(std::env::var("OUT_DIR")?);

    const PROBES: &[&str] = &["execve", "memory", "persistence", "privesc", "rootkit"];

    for probe in PROBES {
        let src = probes_dir.join(format!("{probe}.bpf.c"));
        let dst = out_dir.join(format!("{probe}.skel.rs"));

        SkeletonBuilder::new()
            .source(&src)
            // libbpf headers are typically under `/usr/include/bpf` on
            // Debian/Ubuntu (libbpf-dev). `vmlinux.h` is generated by CI in
            // `arqenor-ebpf/src/probes/vmlinux.h` and #included by the .bpf.c
            // probes from the same directory.
            .clang_args(["-I/usr/include/bpf", "-I/usr/include"])
            .build_and_generate(&dst)
            .map_err(|e| format!("failed to build {}: {e}", src.display()))?;

        // Re-run the script if the C source changes.
        println!("cargo:rerun-if-changed={}", src.display());
    }

    println!("cargo:rerun-if-changed=src/probes/vmlinux.h");
    println!("cargo:rerun-if-changed=build.rs");

    Ok(())
}

#[cfg(not(target_os = "linux"))]
fn main() {}
